apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: primes-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: primes
  minReplicas: 4
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60