apiVersion: apps/v1
kind: Deployment
metadata:
  name: primes
  labels:
    app: primes
spec:
  replicas: 4
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 0%
  selector:
    matchLabels:
      app: primes
  template:
    metadata:
      labels:
        app: primes
    spec:
      containers:
        - name: primes
          image: alexksbr/primes:1.0
          ports:
            - containerPort: 4000